version: "3.9"

services:
  database_car_rental: 
    image: postgres
    container_name: database_car_rental
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=car_rental
    volumes: 
      - pgdata:/data/postgres

  app:
    build: .
    container_name: car_rental
    restart: always
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_car_rental  
    depends_on:
      - database_car_rental

volumes:
  pgdata: 
    driver: local
